services:
  postgres-customers-db:
    container_name: postgres-customers-db
    image: postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - infra_default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers
      PGDATA: /data/postgres/customers
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - db:/data/postgres/customers
    ports:
      - "5432:5432"
    restart: unless-stopped

  customers-api:
    image: jfora/customers
    networks:
      - infra_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`api.jaafarfora.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_HOST: postgres-customers-db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    depends_on:
      - postgres-customers-db

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true

networks:
  infra_default:
    external: true

volumes:
  db:
