services:
  db:
    container_name: postgres-customers-db
    image: postgres
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: customers-db-user
      POSTGRES_PASSWORD: customers-db-password
      PGDATA: /data/postgres/customers
    volumes:
      - db:/data/postgres/customers
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  customers-api:
    image: customers/customers:1.0.0
    ports:
      - 8080:8080
    networks:
      - spring-demo
    depends_on:
      - db
networks:
  spring-demo:
    driver: bridge

volumes:
  db: