server:
  port: 8080
  error:
    include-message: always

spring:
  config:
    import: "optional:configtree:/etc/config/"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/customers
    username: ${POSTGRES_USER_FILE:/run/secrets/postgres_user}
    password: ${POSTGRES_PASSWORD_FILE:/run/secrets/postgres_password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
